version: 0.1.{build}
branches:
  only:
  - master
  - /release.*/
image: Visual Studio 2017 Preview
configuration: Release
before_build:
- cmd: dotnet restore
build:
  parallel: true
  verbosity: detailed
